### ISSUE TITLE
Sub-scopes in Rails 4

### ISSUE THREAD

**Issue by sanfordredlich** [mrkamel/search_cop#13]
Thanks for this! I'd like to optimize my query by using scope (see "scope { joins(:author).eager_load(:comments) } # etc." in the docs). That formulation doesn't work in Rails 4. Can you update with tips on what would work for Rails 4?

**Comment by mrkamel** [comment]
Which version of rails are you using exactly ... 4.0/4.1/4.2? Moreover, could you provide a bit more info what exactly doesn't work for you. A Backtrace and/or SQL generated by Search Cop would help. Thx.

**Comment by mrkamel** [comment]
Your full SearchCop declaration will also be helpful. Thx.

**Comment by mrkamel** [comment]
Do you have any news regarding this issue?

**Comment by mrkamel** [comment]
Hi, as you did not provide more details, i'm closing this issue.
You're of course still welcome to provide further info.
