### ISSUE TITLE
The search is not related models

### ISSUE THREAD

**Issue by Wadik** [mrkamel/search_cop#17]
I have 2 models. They are not related. 

class Event < ActiveRecord::Base
end

class Movie < ActiveRecord::Base
end

How to search for both events.title and movies.name?

**Comment by mrkamel** [comment]
As SearchCop simply generates SQL, you can always use sql's UNION to search/query multiple unrelated tables/models at the "same" time.

ActiveRecord already ships with a union method, but it currently (Rails 4.2) "still" doesn't yet return an ActiveRecord::Relation.

See:

http://makandracards.com/bonyiii/24302-activerecord-union-with-arel
https://github.com/rails/rails/issues/939

**Comment by Wadik** [comment]
Thank you!
