### ISSUE TITLE
Inappropriate searches for dates and times

### ISSUE THREAD

**Issue by mainej** [mrkamel/search_cop#18]
Because of the following, search_cop will turn a search for "xyz09@example.com" into a range search on [date](https://github.com/mrkamel/search_cop/blob/master/lib/search_cop_grammar/attributes.rb#L231-L233) and [time](https://github.com/mrkamel/search_cop/blob/master/lib/search_cop_grammar/attributes.rb#L231-L233) fields.

```ruby
::Time.parse("xyz09@example.com") #=> 2015-03-09 00:00:00 +0000
::Date.parse("xyz09@example.com") #=> Mon, 09 Mar 2015
```

One possible fix would be to use [strptime](http://ruby-doc.org/stdlib-2.1.1/libdoc/date/rdoc/Date.html#method-c-strptime) with a documented format.

**Comment by mrkamel** [comment]
thanks for the report. right, it seems, like we have to use a white-list approach such that we can support a limit set of pre-defined date/time formats only.
