### ISSUE TITLE
query association two levels deep

### ISSUE THREAD

**Issue by navjeetc** [mrkamel/search_cop#19]
I have a person model that has many identifications (Identification model has an attribute number) and each identification has an identification_type (IdentificationType model has an attribute name)

I want to search for all people that have a identification number of 12345678 and identification_type that has a name of 'ssn'. Can this be accomplished in search_cop?

**Comment by navjeetc** [comment]
My current solution is
Add this to Identification model
```ruby
search_scope :search do
    attributes :number
    attributes :type => "identification_type.name"
  end
```
And query for Person like following:
```ruby

Person.joins(:identifications).where("identifications.id in (?)", 
      Identification.search(number: query, type: "ssn").collect{|i| i.id})
```

but I have a feeling there is a better solution

**Comment by mrkamel** [comment]
You have multiple options, depending on your needs.
However, please note that this is not really search_cop specific, but SQL/ActiveRecord specific.
If it's possible in SQL, it should be possible with search_cop as well.
I'm not 100% sure if i understand your schema correctly, but what about:

```ruby
class Person
  has_many :identifications
  has_many :identification_types, :through => :identifications

  search_scope :search do
    attributes :number
    attributes :type => "identification_types.name"
  end
end

Person.search(number: ..., type: ...)
```
