### ISSUE TITLE
conflict with ransack

### ISSUE THREAD

**Issue by navjeetc** [mrkamel/search_cop#20]
My web app uses Active Admin that uses ransack. I cannot seem to use Search Cop as Ransack uses the search method. Is there any way to avoid conflict with search method in Search Cop and ransack?

**Comment by navjeetc** [comment]
I was able to fix this by adding an initializer for ransack
```ruby
Ransack::Adapters::ActiveRecord::Base.class_eval('remove_method :search')
```

**Comment by mrkamel** [comment]
Well, it's up to you how to name the method that search_cop adds:

```ruby
  search_scope :search do
    # ..
  end
```

You can choose the name `:search` as you like
