### ISSUE TITLE
Will this conform to Rails5?

### ISSUE THREAD

**Issue by kentarohorie** [mrkamel/search_cop#30]
There are that plan?

**Comment by mrkamel** [comment]
sure, rails 5.0 should be supported. Had a gemfile for it for quite some time, just didn't add it to travis, as rails 5 requires ruby > 2.2 and the search_cop travis setup still supports 1.9. However, i managed to add it now. Everything should be fine. I'm not using rails 5 myself in production yet, but if you encounter issues regarding rails 5/search_cop don't hesitate reporting them.
