### ISSUE TITLE
Array operators

### ISSUE THREAD

**Issue by rubendinho** [mrkamel/search_cop#31]
Thanks for a terrific gem.  

If there a way to search through PG array attributes?  If not, are there any plans to add support this: https://www.postgresql.org/docs/9.6/static/functions-array.html

In particular, I'm trying to use `@>` operators to search through a text array.

**Comment by mrkamel** [comment]
Somewhat similar to #28

Up until now search_cop tried to stay database agnostic. But, i'll check if/how we can support database specific datatypes.
