### ISSUE TITLE
undefined method 'visit_SearchCopGrammar_Nodes_MatchesFulltext'

### ISSUE THREAD

**Issue by hoenth** [mrkamel/search_cop#32]
First, I want to thank you for your excellent library. 
Unfortunately, I am encountering an issue which I can't figure out. 

When a user submits a query that includes spaces, the server responds with

undefined method 'visit_SearchCopGrammar_Nodes_MatchesFulltext'
with the following backtrace. 
````
search_cop (1.0.6) lib/search_cop/visitors/visitor.rb:15:in `visit'
search_cop (1.0.6) lib/search_cop/visitors/visitor.rb:23:in `block in visit_SearchCopGrammar_Nodes_Or'
search_cop (1.0.6) lib/search_cop/visitors/visitor.rb:23:in `collect'
search_cop (1.0.6) lib/search_cop/visitors/visitor.rb:23:in `visit_SearchCopGrammar_Nodes_Or'
search_cop (1.0.6) lib/search_cop/visitors/visitor.rb:15:in `visit'
search_cop (1.0.6) lib/search_cop/visitors/visitor.rb:55:in `visit_SearchCopGrammar_Nodes_Not'
search_cop (1.0.6) lib/search_cop/visitors/visitor.rb:15:in `visit'
search_cop (1.0.6) lib/search_cop/visitors/visitor.rb:19:in `block in visit_SearchCopGrammar_Nodes_And'
search_cop (1.0.6) lib/search_cop/visitors/visitor.rb:19:in `collect'
search_cop (1.0.6) lib/search_cop/visitors/visitor.rb:19:in `visit_SearchCopGrammar_Nodes_And'
search_cop (1.0.6) lib/search_cop/visitors/visitor.rb:15:in `visit'
search_cop (1.0.6) lib/search_cop/query_builder.rb:12:in `initialize'
search_cop (1.0.6) lib/search_cop.rb:61:in `new'
search_cop (1.0.6) lib/search_cop.rb:61:in `unsafe_search_cop'
search_cop (1.0.6) lib/search_cop.rb:53:in `search_cop'
search_cop (1.0.6) lib/search_cop.rb:44:in `block in search_scope'
````

I am running Mysql 5.6 and have set up my model with the following options:
````
  search_scope :search do
    attributes :question, :answer

    options :question, :type => :fulltext
    options :answer, :type => :fulltext
  end
````

I have verified that the fulltext indexes for question and answer are in place. 

I am calling search scope with the following:
````
  Help.search(params[:q])
````

I do not encounter this issue when running in development locally. 

Any ideas you have as to what is causing this error would be greatly appreciated

**Comment by mrkamel** [comment]
Hi,

seems to be an issue with NOT queries like `word1 -word` in fulltext mode when you have multiple fultext indices and you don't specify a specific field `word1 -answer:word2`. I pushed a fix in branch `fulltext_fix_32`. Could you try that out?

---

BTW i'd like to suggest creating a single, compound fulltext index on question + answer and specify, as search cop can optimize that far better:

```ruby
search_scope :search do
  attributes all: [:question, :answer]

  options :all, :type => :fulltext, :default => true
end
```

**Comment by mrkamel** [comment]
Please use branch `fulltext_fix_32_2`.

**Comment by hoenth** [comment]
Hi @mrkamel - Thank you so much for your quick reply and fix. I have deployed the fulltext_fix_32_2 branch, and made the change to use the compound index. 

And I am no longer seeing that error.
