### ISSUE TITLE
Ability to validate search string without making query

### ISSUE THREAD

**Issue by bpatram** [mrkamel/search_cop#33]
Is there a way to validate a search string/query for a specific search scope? 

For example if I have a search_scope of the following:
```ruby
# my_model.rb MyModel
search_scope :search do
  attributes :value # value is an integer attribute type (not string)
  options :value, default: true
end
```

It would be nice to be able to call something like `MyModel.validate_search("value:Foo")` which would not actually make a query to the database but either raise an error (like the`IncompatibleDatatype` error) or return a boolean value.

This would allow us to validate/verify queries before being run and handle errors rather than silently failing when calling `search("value:Foo")` as it does now. The `unsafe_search` method is nice, but if there was a way to separate validation from querying that would be great.

My primary reason for this request is to better handle errors when using custom filters in the [jsonapi_resources gem which has a custom `verify` method](http://jsonapi-resources.com/v0.10/guide/resources.html#Verifying-Filters).

**Comment by bpatram** [comment]
After digging into the code this may seem fairly trivial to add to the `SearchCop` module as another ClassMethod. Unfortunately I don't think I'll have the time to make a proper PR this weekend.

```ruby
# raises an error or returns the query
def validate_search_scope(query, scope_name)
  SearchCop::QueryBuilder.new(self, query, search_scopes[scope_name])
  query
end
```

**Comment by mrkamel** [comment]
sounds reasonable, i'll take a look at it asap.

**Comment by mrkamel** [comment]
Well, you actually can simply do `MyModel.unsafe_search("query").to_sql` or `MyModel.unsafe_search("query")`. As SearchCop returns an `AR::Relation` the query of course gets lazily evaluated. So i'm not sure adding `validate_search_cop!` provides much benefit.
