### ISSUE TITLE
Rails 5 Support

### ISSUE THREAD

**Issue by fuzzygroup** [mrkamel/search_cop#36]
Hi, 

I'm considering this for a new API I'm building and I noticed that the home page mentions Rails 3 and Rails 4 only.  Are there issues with Rails 5 or are you just assuming that's the defaut?

Thanks!

**Comment by mrkamel** [comment]
Related to #30.

Just not updated the readme, yet. It should support Rails 5 without issues. If you encouter any issues, please report.

**Comment by mrkamel** [comment]
README changed
