### ISSUE TITLE
Error when using with non-standard pluralization in class name

### ISSUE THREAD

**Issue by kuzmik** [mrkamel/search_cop#53]
My class for windows devices is named `Device::Windows`, rather than `Device::Window`... becuase Window isn't the OS name. Device::Mac works great with search_cop though :)

```ruby
class Device::Windows < ApplicationRecord
  include SearchCop

  search_scope :search do
    attributes :serial_number, :hostname
  end
end
```

```ruby
bc-windows:development [44] pry(main)> Device::Windows.search('kuzmik')
NameError: uninitialized constant Device::Window
from /Users/kuzmik/.rbenv/versions/2.6.5/gemsets/widows/gems/activesupport-5.2.4/lib/active_support/inflector/methods.rb:285:in `const_get'
windows:development [45] pry(main)>
```

I tried setting up inflections in the rails initializer, but it didn't seem to do the trick.
```ruby
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.plural 'Device::Windows', 'Device::Windows'
  inflect.singular 'Device::Windows', 'Device::Windows'
end
```

I assume it's something silly I have misconfigured somewhere, but any help you can provide would be appreciated. I'd love to drop ransack and use search_cop instead!

**Comment by mrkamel** [comment]
hi, please try to add inflections for `"device/windows"`.

**Comment by kuzmik** [comment]
thank did the trick! thank you much.
