### ISSUE TITLE
DEPRECATION WARNING

### ISSUE THREAD

**Issue by Bilal-Abbas** [mrkamel/search_cop#54]
DEPRECATION WARNING: #search is deprecated and will be removed in 2.3, please use #ransack instead (called from __pry__ at (pry):21)

**Comment by mrkamel** [comment]
not very detailed, unfortunately, but i think this is due to how you named your search scope

**Comment by Bilal-Abbas** [comment]
I have solved my problem.
This problem was due to not using search in many to many associations using through
I have fixed it.
In my organization modal, I have
`has_many :subscribers, through: :organization_subscriptions, source: :user`
and my organization_subscriptions modal has
`belongs_to :user
  belongs_to :organization`

I simply add the following and it worked in the console as well as in developement
`search_scope :search do
      attributes user: ["user.user_id"]
  end`
