### ISSUE TITLE
How to handle special search logic / virtual attributes

### ISSUE THREAD

**Issue by DannyBen** [mrkamel/search_cop#55]
Hi,

I am not sure if this is related to #14 or not, but since that issue is old, I figured I will ask here.

I just started testing search_cop, and immediately bumped into two special cases that I am not sure how to solve (if at all possible):

### Case 1: Full name virtual attribute

My model has `first_name` and `last_name`, and I would like to allow searching using

```ruby
Member.search "name:'James Bond'"
```

### Case 2: Local phone number virtual attribute

My model stores phone numbers using the full international format, but I would like to allow searching by using a local format. The local format is prefixed with a 0, while the international value is not.

Prior to using search_cop, I achieved both with something like the below:

```ruby
def self.search(query)
  normalized_phone = query.phony_normalized || query
  where "
    members.phone ilike ?
    or (members.first_name || ' ' || members.last_name) ilike ?",
    "%#{normalized_phone}%", "%#{query}%", "%#{query}%"
end
```

Is there anything I missed in the documentation to allow this flexibility?

**Comment by mrkamel** [comment]
hi,

case 1:

you can use a group:

```ruby
seach_scope ... do
  attributes name: [:first_name, :last_name]
end
```

but it'll not allow you to search using the mentioned quoted query.
However, you'll be able to search for `Model.search("James Bond")`

case 2:

currently, i'd try to detect/parse phone numbers and un-prefix them before passing them to search cop.

In addition, recall that you can chain/combine multiple queries:

```ruby
search_scope :name_search do 
  attributes name: [:first_name, :last_name]
end

search_scope :phone_search do
  attributes :phone
end
```

and then

```ruby
Model.name_search('James Bond').or(Model.phone_search(normalize_phone('0123456789')))
```

**Comment by DannyBen** [comment]
Thank you, but both beats ~the~ my purpose. I was looking to provide my users with a single search field, where they can just type advanced queries, and it will be executed in one scope. Sort of like GitHub is doing. So in my case, I wanted users to type in one field:

```
name:'James Bond' phone:0551234567
```

After posting this issue, I also noticed that the intuitive syntax for setting **exact match** did not work. When searching for `first_name: bob`, we also get users named `Bobby`, and I was assuming `name: "bob"` would match exact match, but it didn't.

So, unless I am missing something, I am a bit discouraged about this gem fulfilling my needs.

**Comment by mrkamel** [comment]
hi, unfortunate to hear, but yeah. i try to support as many use cases as possible... In general, search_cop is not a fulltext search unless you tell search cop to use fulltext mode (see readme). In non-fulltext mode it's using LIKE queries and, yes, will match `Bobby`. I'll consider adding a concatenation option to support the fullname use case, but it'll of course take some time. Same for custom mappers, still.

**Comment by DannyBen** [comment]
Yeah, totally understood. It is still a great gem and I was hoping it can do what I need, since such search is common both in GitHub, and Gmail for example.

In fact, I reached the gem by searching "rails search like github"... :)

Thanks for being cool about it all, I am closing.
