### ISSUE TITLE
Suggestion: Option for `exact: true` (or `right_wildcard: false`)

### ISSUE THREAD

**Issue by DannyBen** [mrkamel/search_cop#56]
Hi,

I have noticed that exact search was somewhat discussed in #23, but I think this issue is different.

I know there is the option to disable left wildcard, but:

- I did not find an option to disable right wildcard, or even better;
- I was hoping to have an option that is called `exact`, that disables both left and right wildcards.

```ruby
search_scope :search do
  attributes :first_name, :last_name, :location
  # was hoping for this:
  options :location, exact: true
  # or at least this:
  options :location, left_wildcard: false, right_wildcard: false
end
```

**Comment by mrkamel** [comment]
available in master now
