### ISSUE TITLE
Words containing brackets

### ISSUE THREAD

**Issue by ttekesuke** [mrkamel/search_cop#76]
I tried search_cop (1.2.3).
I can't search for words containing brackets, like "(" or ")". 
Perhaps the sql query is not being executed.
Any ideas?

**Comment by mrkamel** [comment]
hi, thanks for reporting. brackets are operators in search cop. Try to put it in quotes:

```
title:"title with ( brackets"
```

**Comment by ttekesuke** [comment]
Thank you. I could search ( with quotes.
BTW, if there are space characters in the search string, if the search string is not enclosed in quotes, 
a query will be issued that connects a group of strings divided by spaces with the AND condition.
```
SELECT * FROM "items" WHERE (
    (("items"."title" IS NOT NULL AND "items"."title" ILIKE '%title%') OR ("items"."sub_title" IS NOT NULL AND "items"."sub_title" ILIKE '%title%')) AND 
    (("items"."title" IS NOT NULL AND "items"."title" ILIKE '%with%') OR ("items"."sub_title" IS NOT NULL AND "items"."sub_title" ILIKE '%with%')) AND 
    (("items"."title" IS NOT NULL AND "items"."title" ILIKE '%brackets%') OR ("items"."sub_title" IS NOT NULL AND "items"."sub_title" ILIKE '%brackets%'))
)
```
However, if I enclose the search string in quotes, it seems that the spaces are also considered as strings 
and are searched as a single chunk.
```
SELECT * "items" WHERE (
    (("items"."title" IS NOT NULL AND "items"."code" ILIKE '%title with brackets%') OR ("items"."sub_title" IS NOT NULL AND "items"."sub_title" ILIKE '%title with brackets%'))
)
```
Is there any way to connect strings with spaces with the AND condition and also search for bracket strings?

**Comment by mrkamel** [comment]
That's not possible atm, sry. Search cop orients on fulltext engines. The quotes are also an operator and try to match a field exactly. Adding an escaping feature (`title:some\(word`) would maybe help here, but would not be working with supported fulltext modes (postgres, mysql) easily and searching for words with brackets seems to rather be an edge case. I'm not strictly against such escaping feature, but i won't implement it myself.

**Comment by ttekesuke** [comment]
OK, thank you!
