### ISSUE TITLE
undefined method `visit_SearchCopGrammar_Nodes_FulltextExpression' for an instance of SearchCop::Visitors::Visitor

### ISSUE THREAD

**Issue by andrewkendall** [mrkamel/search_cop#80]
I've started to see a new issue which throws the error:

`undefined method visit_SearchCopGrammar_Nodes_FulltextExpression for an instance of SearchCop::Visitors::Visitor`

It's trigger by:

```
  search_scope :search do
    attributes :title, :content
    options :title, type: :fulltext # This is the cause, removing stops the error
  end
```

It seems to have happened around the time of the Rails 7.1 and Ruby 3.3 upgrade I performed.

I'm trying to track down the exact cause now, but thought I would post in case anyone else is seeing the same.

**Comment by andrewkendall** [comment]
It looks like I've found the cause it's moving from the Mysql2 gem to Trilogy (https://github.com/trilogy-libraries/trilogy).

As far as I understand, Trilogy is set to be the new default in Rails 8.

**Comment by mrkamel** [comment]
thanks for opening. i'll check asap

**Comment by mrkamel** [comment]
will be fixed via https://github.com/mrkamel/search_cop/pull/81

**Comment by andrewkendall** [comment]
Excellent work! All looking good.
